### ISSUE TITLE
lark==1.0.0 breaks Package

### ISSUE THREAD

**Issue by evandrix** [theY4Kman/parsuricata#13]
version just before `lark==0.12.0` works
```
Traceback (most recent call last):
  File "run.py", line <N>, in <module>
    import parsuricata
  File "/usr/local/lib/python3.9/site-packages/parsuricata/__init__.py", line 3, in <module>
    from ._parser import parser
  File "/usr/local/lib/python3.9/site-packages/parsuricata/_parser.py", line 3, in <module>
    from .transformer import RuleTransformer
  File "/usr/local/lib/python3.9/site-packages/parsuricata/transformer.py", line 4, in <module>
    from lark import InlineTransformer, Token, Tree
ImportError: cannot import name 'InlineTransformer' from 'lark' (/usr/local/lib/python3.9/site-packages/lark/__init__.py)
```

**Comment by theY4Kman** [comment]
Hmm, it looks like the 1.0.0 version differs in more ways than just import paths. Is there a specific reason you want to use `lark>=1.0.0`?

**Comment by evandrix** [comment]
nope, just typical habit to upgrade to latest packages esp. for any security patches
